feat(portal): show "browser not supported" message
MystenLabs/walrus-sites pull request #103
Opened 2024-06-25 12:00 UTC by giac-mysten

Closes: #91

2024-06-26 08:54 UTC, xydas97 requested changes
Minor styling changes:

![image](https://github.com/MystenLabs/walrus-sites/assets/105368040/00a39991-b649-4d86-939c-228304b9a082)
![image](https://github.com/MystenLabs/walrus-sites/assets/105368040/00a39991-b649-4d86-939c-228304b9a082)

2024-06-26 08:54 UTC, xydas97 commented on portal/static/walrus-sites-portal-register-sw.js
> +    h3.textContent = title;
```suggestion
    h3.textContent = title;
    h3.className = "InterTightMedium";
```

2024-06-26 08:54 UTC, xydas97 commented on portal/static/walrus-sites-portal-register-sw.js
> +    p.textContent = subtitle;
```suggestion
    p.textContent = subtitle;
    p.className = "InterTightMedium";
    p.style.color = "#696969";
    p.style.fontSize = "18px";
```

2024-06-27 08:49 UTC, giac-mysten commented
Thanks @xydas97 for the suggestions!

2024-07-03 10:12 UTC, xydas97 approved these changes
LGTM!

2024-07-05 03:05 UTC, merged