WIP: Add deletable flag in warlus store assets upload
MystenLabs/walrus-sites pull request #320
Opened 2024-12-06 21:29 UTC by VLegakis

site-builder `delete` command needs to be added.

2024-12-07 11:16 UTC, Tzal3x requested changes
Welcome to the project @VLegakis! 
Despite this being still a WIP, here is an early comment: 
Regarding deletable sites in walrus, based on [this](https://github.com/MystenLabs/walrus-sites/pull/318#issuecomment-2520314525) discussion,  we might need the opposite of what is implemented currently. 
i.e. instead of publishing sites as deletable with a `--deletable` flag, we should always publish them as deletable by default, unless specified otherwise with `--permanent`.

2024-12-07 11:23 UTC, Tzal3x commented
Also, please check out [CONTRIBUTING.md](https://github.com/MystenLabs/walrus-sites/blob/main/CONTRIBUTING.md) and follow how to set your `.editorconfig` in order to automatically resolve lint errors like it's happening now.

2024-12-09 16:02 UTC, giac-mysten commented
> @giac-mysten do you think --only-expirable instead of --permanent would better depict the actual site lifetime being set?

@Tzal3x good question. "Permanent" is official Walrus terminology. When you `walrus store <FILE>`, the output says "Success: Permanent blob stored successfully."

So i'd say `--permanent` is fine.

2024-12-11 13:14 UTC, Tzal3x commented
@VLegakis since you rebased your branch to `gg/site-builder/update-package-and-burn` your PR should point to `gg/site-builder/update-package-and-burn` and not `main`.

2024-12-11 13:15 UTC, VLegakis commented
> @VLegakis since you rebased your branch to `gg/site-builder/update-package-and-burn` your PR should point to `gg/site-builder/update-package-and-burn` and not `main`.

Yes I know. Done

2025-01-20 11:16 UTC, giac-mysten reviewed
Thanks @VLegakis ! this is really nice. I added some suggestions for improvement, and a few questions. Lmk what you think!

2025-01-20 11:16 UTC, giac-mysten commented on site-builder/src/site/manager.rs
> +            display::done();
Remark: i noticed and interesting problem here. If you store a site with `permanent = true`, and then run destroy, you still get `deleting resource ... [Ok]`, which is a bit misleading. This is because the terminal returns, but `deletedBlobs` is an empty vector.

Could we add a check here, and if no deletable blobs are found, print it out with a warning?

2025-01-21 17:50 UTC, VLegakis reviewed
Handled comments

2025-01-21 17:50 UTC, VLegakis commented on site-builder/src/main.rs
> +                false,
Adrressed in publish.rs

2025-01-21 17:50 UTC, VLegakis commented on site-builder/src/publish.rs
> +            false,
Addressed this here. So now it respects permanent flag

2025-01-21 17:50 UTC, VLegakis commented on site-builder/src/walrus/output.rs
> +    deletedBlobs: Box<[String]>,
I have changed that to Vec<String>
I read that Box<[String]> is a bit more memory efficient and used it but I gues it doesn't make much difference.

2025-01-21 17:50 UTC, VLegakis commented on site-builder/src/site/manager.rs
> +            display::done();
Fixed that. Actually in case all_dynamic_fields I print a warning and don't delete anything. Let me know if that works

2025-01-31 09:07 UTC, giac-mysten approved these changes
one last nit! 🙏 but looks good :)

2025-01-31 09:07 UTC, giac-mysten commented on site-builder/src/site/manager.rs
> +            display::done();
what i meant is: we don't check that `_output` actually contains the blob id! we should check that, see that it matches the one we wanted to delete. if there is no blob id, then we can print "could not delete this blob, may be already deleted or may be permanent..." or something similar.

2025-01-31 13:34 UTC, VLegakis commented
> one last nit! 🙏 but looks good :)

I've addressed that with:
```
if output.objectId != *blob_id.to_string() {
                display::error(format!(
                    "Could not delete blob {}, may be already deleted or may be a permanent blob",
                    blob_id
                ));
            }
```
Please take a look and let me know in order to merge

2025-01-31 13:39 UTC, merged